name: phonedine
description: "連絡先と位置情報を活用した店舗検索アプリ"

publish_to: 'none'
version: 1.0.5+6
environment:
  sdk: '>=3.2.3 <4.0.0'
dependencies:
  flutter:
    sdk: flutter
  url_launcher: ^6.3.1
  flutter_dotenv: ^5.1.0
  cupertino_icons: ^1.0.2
  google_maps_flutter: ^2.12.1
  google_place: ^0.4.7
  geolocator: ^13.0.4
  http: ^0.13.6
  permission_handler: ^11.3.0
  flutter_contacts: ^1.1.7+1
  location: ^5.0.3
  flutter_localizations:
    sdk: flutter
dev_dependencies:
  change_app_package_name: ^1.0.0
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
flutter:
  uses-material-design: true
  generate: true
  assets:
    - .env

